name: Code Checks

on:
    push:
        branches: [ master, develop ]
    pull_request:
        branches: [ master ]
          
jobs:
    Lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ 3.12, 3.10.12 ]
        steps:
            - name: Linter
              uses: actions/checkout@v2
              with:
                python-version: ${{ matrix.python-version }}

            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip --break-system-packages
                  python3 -m pip install types-psutil --break-system-packages
                  pip3 install -r requirements.txt --break-system-packages
                  python3 -m pip install flake8

            - name: Flake8
              run: |
                  clear && flake8 --extend-ignore E501,F405

    Tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ 3.12, 3.10.12 ]
        steps:
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip --break-system-packages
                  python3 -m pip install types-psutil --break-system-packages
                  pip3 install -r requirements.txt --break-system-packages
            - name: MyPy
              run: |
                  mypy .
