name: Code Checks

on:
    push:
        branches: [ master, develop ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ 3.12 ]
        steps:
            - uses: actions/checkout@v4
            - name: Linter
              uses: sunnysid3up/python-linter@master
              with:
                source: "src"
                mypy-options: "--ignore-missing-imports --show-error-codes"
                pylint-options: "--rcfile=setup.cfg"
                isort-options: "-w 100"
            - uses: actions/checkout@v2
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                  python3 -m pip install --upgrade pip --break-system-packages
                  python3 -m pip install types-psutil --break-system-packages
                  pip3 install -r requirements.txt --break-system-packages
            - name: MyPy
              run: |
                  mypy .
